from _typeshed import Incomplete

from ..binding import BindingError as BindingError
from ..binding import BindingMixin as BindingMixin
from .exception import ExecutionError as ExecutionError

class Driver(BindingMixin):
    logger: Incomplete
    def __attrs_post_init__(self) -> None: ...
    def get_priority(self, protocol): ...
    def get_export_name(self): ...
    def get_export_vars(self): ...
    @property
    def skip_deactivate_on_export(self): ...
    def get_bound_resources(self): ...

def check_file(filename, *, command_prefix=[]) -> None: ...
