from ..step import step as step
from ..util import PtxExpect as PtxExpect
from ..util import Timeout as Timeout
from .common import Driver as Driver

class ConsoleExpectMixin:
    def __attrs_post_init__(self) -> None: ...
    @Driver.check_active
    def read(self, size: int = 1, timeout: float = 0.0, max_size=None): ...
    @Driver.check_active
    def write(self, data): ...
    @Driver.check_active
    def sendline(self, line) -> None: ...
    @Driver.check_active
    def sendcontrol(self, char) -> None: ...
    @Driver.check_active
    def expect(self, pattern, timeout: int = -1): ...
    @Driver.check_active
    def settle(self, quiet_time, timeout: float = 120.0) -> bool: ...
    def resolve_conflicts(self, client) -> None: ...
