from _typeshed import Incomplete

from ..factory import target_factory as target_factory
from ..step import step as step
from ..util.helper import processwrapper as processwrapper
from ..util.managedfile import ManagedFile as ManagedFile
from .common import Driver as Driver

class DFUDriver(Driver):
    bindings: Incomplete
    tool: Incomplete
    def __attrs_post_init__(self) -> None: ...
    def on_activate(self) -> None: ...
    def on_deactivate(self) -> None: ...
    @Driver.check_active
    def download(self, altsetting, filename) -> None: ...
    def detach(self, altsetting) -> None: ...
    def list(self) -> None: ...
