from _typeshed import Incomplete

from ..factory import target_factory as target_factory
from ..protocol import ConsoleProtocol as ConsoleProtocol
from ..protocol import PowerProtocol as PowerProtocol
from ..step import step as step
from .common import Driver as Driver
from .consoleexpectmixin import ConsoleExpectMixin as ConsoleExpectMixin
from .exception import ExecutionError as ExecutionError
from .powerdriver import PowerResetMixin as PowerResetMixin

class LAASerialDriver(ConsoleExpectMixin, Driver, ConsoleProtocol):
    bindings: Incomplete
    txdelay: Incomplete
    timeout: Incomplete
    def __attrs_post_init__(self) -> None: ...
    def on_activate(self) -> None: ...
    def on_deactivate(self) -> None: ...

class LAAPowerDriver(Driver, PowerResetMixin, PowerProtocol):
    bindings: Incomplete
    delay: Incomplete
    def __attrs_post_init__(self) -> None: ...
    def on_activate(self) -> None: ...
    def on_deactivate(self) -> None: ...
    @Driver.check_active
    def on(self) -> None: ...
    @Driver.check_active
    def off(self) -> None: ...
    @Driver.check_active
    def cycle(self) -> None: ...

class LAAUSBGadgetMassStorageDriver(Driver):
    bindings: Incomplete
    def __attrs_post_init__(self) -> None: ...
    def on_activate(self) -> None: ...
    def on_deactivate(self) -> None: ...
    @Driver.check_active
    def on(self) -> None: ...
    @Driver.check_active
    def off(self) -> None: ...

class LAAUSBDriver(Driver):
    bindings: Incomplete
    def __attrs_post_init__(self) -> None: ...
    def on_activate(self) -> None: ...
    def on_deactivate(self) -> None: ...
    @Driver.check_active
    def on(self) -> None: ...
    @Driver.check_active
    def off(self) -> None: ...

class LAAButtonDriver(Driver):
    bindings: Incomplete
    def __attrs_post_init__(self) -> None: ...
    def on_activate(self) -> None: ...
    def on_deactivate(self) -> None: ...
    @Driver.check_active
    def press(self, button) -> None: ...
    @Driver.check_active
    def release(self, button) -> None: ...

class LAALedDriver(Driver):
    bindings: Incomplete
    def __attrs_post_init__(self) -> None: ...
    def on_activate(self) -> None: ...
    def on_deactivate(self) -> None: ...
    @Driver.check_active
    def on(self) -> None: ...
    @Driver.check_active
    def off(self) -> None: ...

class LAATempDriver(Driver):
    bindings: Incomplete
    def __attrs_post_init__(self) -> None: ...
    def on_activate(self) -> None: ...
    def on_deactivate(self) -> None: ...
    @Driver.check_active
    def get_temp(self, probe): ...

class LAAWattDriver(Driver):
    bindings: Incomplete
    def __attrs_post_init__(self) -> None: ...
    def on_activate(self) -> None: ...
    def on_deactivate(self) -> None: ...
    @Driver.check_active
    def get_watts(self, vbus): ...

class LAAProviderDriver(Driver):
    bindings: Incomplete
    def __attrs_post_init__(self) -> None: ...
    def on_activate(self) -> None: ...
    def on_deactivate(self) -> None: ...
    @Driver.check_active
    def stage(self, source): ...
    @Driver.check_active
    def list(self): ...
    @Driver.check_active
    def remove(self, name) -> None: ...
