from _typeshed import Incomplete

from ..factory import target_factory as target_factory
from .common import Driver as Driver

class ModbusRTUDriver(Driver):
    bindings: Incomplete
    instrument: Incomplete
    def __attrs_post_init__(self) -> None: ...
    def on_activate(self) -> None: ...
    def on_deactivate(self) -> None: ...
    def read_register(self, *args, **kwargs): ...
    def write_register(self, *args, **kwargs): ...
    def read_registers(self, *args, **kwargs): ...
    def write_registers(self, *args, **kwargs): ...
    def read_bit(self, *args, **kwargs): ...
    def write_bit(self, *args, **kwargs): ...
    def read_string(self, *args, **kwargs): ...
    def write_string(self, *args, **kwargs): ...
