from _typeshed import Incomplete

from ..factory import target_factory as target_factory
from ..protocol import PowerProtocol as PowerProtocol
from ..step import step as step
from ..util import Timeout as Timeout
from .common import Driver as Driver

class MQTTError(Exception): ...

class TasmotaPowerDriver(Driver, PowerProtocol):
    bindings: Incomplete
    delay: Incomplete
    def __attrs_post_init__(self) -> None: ...
    def on_activate(self) -> None: ...
    def on_deactivate(self) -> None: ...
    @Driver.check_active
    def on(self) -> None: ...
    @Driver.check_active
    def off(self) -> None: ...
    @Driver.check_active
    def cycle(self) -> None: ...
    @Driver.check_active
    def get(self): ...
