import contextlib
from collections.abc import Generator

from _typeshed import Incomplete

from ..factory import target_factory as target_factory
from ..resource.remote import RemoteNetworkInterface as RemoteNetworkInterface
from ..step import step as step
from ..util.agentwrapper import AgentWrapper as AgentWrapper
from ..util.ssh import sshmanager as sshmanager
from .common import Driver as Driver
from .exception import ExecutionError as ExecutionError

class NetworkInterfaceDriver(Driver):
    bindings: Incomplete
    wrapper: Incomplete
    def __attrs_post_init__(self) -> None: ...
    ssh: Incomplete
    proxy: Incomplete
    def on_activate(self) -> None: ...
    def on_deactivate(self) -> None: ...
    @property
    def skip_deactivate_on_export(self): ...
    def get_export_vars(self): ...
    @Driver.check_active
    def configure(self, settings) -> None: ...
    @Driver.check_active
    def wait_state(self, expected, timeout: int = 60) -> None: ...
    @Driver.check_active
    def disable(self) -> None: ...
    @Driver.check_active
    def get_active_settings(self): ...
    @Driver.check_active
    def get_settings(self): ...
    @Driver.check_active
    def get_state(self): ...
    @Driver.check_active
    def get_dhcpd_leases(self): ...
    @Driver.check_active
    def request_scan(self): ...
    @Driver.check_active
    def get_access_points(self, scan=None): ...
    @Driver.check_active
    @contextlib.contextmanager
    def forward_local(self, remote_host, remote_port, local_port=None) -> Generator[Incomplete]: ...
    @Driver.check_active
    @contextlib.contextmanager
    def forward_remote(self, remote_port, local_port, remote_bind=None) -> Generator[None]: ...
