from _typeshed import Incomplete

from ..exceptions import InvalidConfigError as InvalidConfigError
from ..factory import target_factory as target_factory
from ..protocol import DigitalOutputProtocol as DigitalOutputProtocol
from ..protocol import PowerProtocol as PowerProtocol
from ..protocol import ResetProtocol as ResetProtocol
from ..resource import NetworkPowerPort as NetworkPowerPort
from ..step import step as step
from ..util.helper import processwrapper as processwrapper
from ..util.proxy import proxymanager as proxymanager
from .common import Driver as Driver
from .exception import ExecutionError as ExecutionError

class PowerResetMixin(ResetProtocol):
    priorities: Incomplete
    def __attrs_post_init__(self) -> None: ...
    @Driver.check_active
    def reset(self) -> None: ...

class ManualPowerDriver(Driver, PowerResetMixin, PowerProtocol):
    @Driver.check_active
    def on(self) -> None: ...
    @Driver.check_active
    def off(self) -> None: ...
    @Driver.check_active
    def cycle(self) -> None: ...

class SiSPMPowerDriver(Driver, PowerResetMixin, PowerProtocol):
    bindings: Incomplete
    delay: Incomplete
    tool: Incomplete
    def __attrs_post_init__(self) -> None: ...
    @Driver.check_active
    def on(self) -> None: ...
    @Driver.check_active
    def off(self) -> None: ...
    @Driver.check_active
    def cycle(self) -> None: ...
    @Driver.check_active
    def get(self): ...

class ExternalPowerDriver(Driver, PowerResetMixin, PowerProtocol):
    cmd_on: Incomplete
    cmd_off: Incomplete
    cmd_cycle: Incomplete
    delay: Incomplete
    @Driver.check_active
    def on(self) -> None: ...
    @Driver.check_active
    def off(self) -> None: ...
    @Driver.check_active
    def cycle(self) -> None: ...

class NetworkPowerDriver(Driver, PowerResetMixin, PowerProtocol):
    bindings: Incomplete
    delay: Incomplete
    backend: Incomplete
    def __attrs_post_init__(self) -> None: ...
    def on_activate(self) -> None: ...
    def set_proxy_from_url(self): ...
    @Driver.check_active
    def on(self) -> None: ...
    @Driver.check_active
    def off(self) -> None: ...
    @Driver.check_active
    def cycle(self) -> None: ...
    @Driver.check_active
    def get(self): ...

class DigitalOutputPowerDriver(Driver, PowerResetMixin, PowerProtocol):
    bindings: Incomplete
    delay: Incomplete
    def __attrs_post_init__(self) -> None: ...
    @Driver.check_active
    def on(self) -> None: ...
    @Driver.check_active
    def off(self) -> None: ...
    @Driver.check_active
    def cycle(self) -> None: ...
    @Driver.check_active
    def get(self): ...

class YKUSHPowerDriver(Driver, PowerResetMixin, PowerProtocol):
    bindings: Incomplete
    delay: Incomplete
    tool: Incomplete
    def __attrs_post_init__(self) -> None: ...
    model: Incomplete
    def on_activate(self) -> None: ...
    @Driver.check_active
    def on(self) -> None: ...
    @Driver.check_active
    def off(self) -> None: ...
    @Driver.check_active
    def cycle(self) -> None: ...
    @Driver.check_active
    def get(self): ...

class USBPowerDriver(Driver, PowerResetMixin, PowerProtocol):
    bindings: Incomplete
    delay: Incomplete
    tool: Incomplete
    def __attrs_post_init__(self) -> None: ...
    @Driver.check_active
    def on(self) -> None: ...
    @Driver.check_active
    def off(self) -> None: ...
    @Driver.check_active
    def cycle(self) -> None: ...
    @Driver.check_active
    def get(self): ...

class PDUDaemonDriver(Driver, PowerResetMixin, PowerProtocol):
    bindings: Incomplete
    delay: Incomplete
    def __attrs_post_init__(self) -> None: ...
    def on_activate(self) -> None: ...
    @Driver.check_active
    def on(self) -> None: ...
    @Driver.check_active
    def off(self) -> None: ...
    @Driver.check_active
    def cycle(self) -> None: ...
    @Driver.check_active
    def get(self) -> None: ...
