from _typeshed import Incomplete

from ..factory import target_factory as target_factory
from .common import Driver as Driver

class PyVISADriver(Driver):
    bindings: Incomplete
    pyvisa_device: Incomplete
    def __attrs_post_init__(self) -> None: ...
    def on_activate(self) -> None: ...
    def on_deactivate(self) -> None: ...
    @Driver.check_active
    def get_session(self): ...
