import contextlib
from collections.abc import Generator

from _typeshed import Incomplete

from ..factory import target_factory as target_factory
from ..resource.common import NetworkResource as NetworkResource
from ..step import step as step
from ..util.agentwrapper import AgentWrapper as AgentWrapper
from ..util.helper import processwrapper as processwrapper
from ..util.managedfile import ManagedFile as ManagedFile
from ..util.netns import NetNamespace as NetNamespace
from ..util.timeout import Timeout as Timeout
from .common import Driver as Driver
from .exception import ExecutionError as ExecutionError

class RawNetworkInterfaceDriver(Driver):
    bindings: Incomplete
    manage_interface: Incomplete
    def __attrs_post_init__(self) -> None: ...
    def on_activate(self) -> None: ...
    def on_deactivate(self) -> None: ...
    @Driver.check_active
    def set_interface_up(self) -> None: ...
    @Driver.check_active
    def set_interface_down(self) -> None: ...
    @Driver.check_active
    def get_state(self): ...
    @Driver.check_active
    def wait_state(self, expected_state, timeout: int = 60) -> None: ...
    @Driver.check_active
    def get_ethtool_settings(self): ...
    @Driver.check_active
    def ethtool_configure(self, **settings) -> None: ...
    @Driver.check_active
    def get_ethtool_eee_settings(self): ...
    @Driver.check_active
    def ethtool_configure_eee(self, **settings) -> None: ...
    @Driver.check_active
    def get_ethtool_pause_settings(self): ...
    @Driver.check_active
    def ethtool_configure_pause(self, **settings) -> None: ...
    @Driver.check_active
    def start_record(self, filename, *, count=None, timeout=None): ...
    @Driver.check_active
    def stop_record(self, *, timeout=None) -> None: ...
    @contextlib.contextmanager
    def record(self, filename, *, count=None, timeout=None) -> Generator[Incomplete]: ...
    @Driver.check_active
    def start_replay(self, filename): ...
    @Driver.check_active
    def stop_replay(self, *, timeout=None) -> None: ...
    @contextlib.contextmanager
    def replay(self, filename, *, timeout=None) -> Generator[Incomplete]: ...
    @Driver.check_active
    def get_statistics(self): ...
    @Driver.check_active
    def get_address(self): ...
    @Driver.check_active
    @contextlib.contextmanager
    def setup_netns(self, mac_address=None) -> Generator[Incomplete, None, Incomplete]: ...
