from _typeshed import Incomplete

from ..factory import target_factory as target_factory
from ..protocol import BootstrapProtocol as BootstrapProtocol
from ..step import step as step
from ..util.helper import processwrapper as processwrapper
from ..util.managedfile import ManagedFile as ManagedFile
from ..util.timeout import Timeout as Timeout
from .common import Driver as Driver

class MXSUSBDriver(Driver, BootstrapProtocol):
    bindings: Incomplete
    image: Incomplete
    tool: Incomplete
    def __attrs_post_init__(self) -> None: ...
    def on_activate(self) -> None: ...
    def on_deactivate(self) -> None: ...
    @Driver.check_active
    def load(self, filename=None) -> None: ...

class IMXUSBDriver(Driver, BootstrapProtocol):
    bindings: Incomplete
    image: Incomplete
    verify: Incomplete
    tool: Incomplete
    def __attrs_post_init__(self) -> None: ...
    def on_activate(self) -> None: ...
    def on_deactivate(self) -> None: ...
    @Driver.check_active
    def load(self, filename=None) -> None: ...

class RKUSBDriver(Driver, BootstrapProtocol):
    bindings: Incomplete
    image: Incomplete
    usb_loader: Incomplete
    tool: Incomplete
    def __attrs_post_init__(self) -> None: ...
    def on_activate(self) -> None: ...
    def on_deactivate(self) -> None: ...
    @Driver.check_active
    def load(self, filename=None) -> None: ...

class UUUDriver(Driver, BootstrapProtocol):
    bindings: Incomplete
    image: Incomplete
    script: Incomplete
    tool: Incomplete
    def __attrs_post_init__(self) -> None: ...
    def on_activate(self) -> None: ...
    def on_deactivate(self) -> None: ...
    @Driver.check_active
    def load(self, filename=None) -> None: ...

class BDIMXUSBDriver(Driver, BootstrapProtocol):
    bindings: Incomplete
    tool: Incomplete
    def __attrs_post_init__(self) -> None: ...
    def on_activate(self) -> None: ...
    def on_deactivate(self) -> None: ...
    @Driver.check_active
    def load(self, filename) -> None: ...
