from _typeshed import Incomplete

from ..exceptions import InvalidConfigError as InvalidConfigError
from ..factory import target_factory as target_factory
from ..util.agentwrapper import AgentWrapper as AgentWrapper
from ..util.agentwrapper import b2s as b2s
from ..util.agentwrapper import s2b as s2b
from .common import Driver as Driver

class USBTMCDriver(Driver):
    bindings: Incomplete
    wrapper: Incomplete
    backend: Incomplete
    index: Incomplete
    def __attrs_post_init__(self) -> None: ...
    def on_activate(self) -> None: ...
    def on_deactivate(self) -> None: ...
    @Driver.check_active
    def command(self, cmd) -> None: ...
    @Driver.check_active
    def query(self, cmd, binary: bool = False, raw: bool = False): ...
    @Driver.check_active
    def identify(self): ...
    @Driver.check_active
    def get_channel_info(self, channel): ...
    @Driver.check_active
    def get_channel_values(self, channel): ...
    @Driver.check_active
    def get_screenshot(self): ...
    @Driver.check_active
    def get_bool(self, cmd): ...
    @Driver.check_active
    def get_int(self, cmd): ...
    @Driver.check_active
    def get_decimal(self, cmd): ...
    @Driver.check_active
    def get_str(self, cmd): ...
