from _typeshed import Incomplete

from ..exceptions import InvalidConfigError as InvalidConfigError
from ..factory import target_factory as target_factory
from ..protocol import VideoProtocol as VideoProtocol
from .common import Driver as Driver

class USBVideoDriver(Driver, VideoProtocol):
    bindings: Incomplete
    def __attrs_post_init__(self) -> None: ...
    def get_qualities(self): ...
    def select_caps(self, hint=None): ...
    def get_pipeline(self, path, caps, controls=None): ...
    @Driver.check_active
    def stream(self, caps_hint=None, controls=None) -> None: ...
