from _typeshed import Incomplete

from .. import Environment as Environment
from ..consoleloggingreporter import ConsoleLoggingReporter as ConsoleLoggingReporter
from ..exceptions import NoStrategyFoundError as NoStrategyFoundError
from ..logging import StepFormatter as StepFormatter
from ..logging import StepLogger as StepLogger
from ..util.helper import processwrapper as processwrapper

LABGRID_ENV_KEY: Incomplete

def pytest_cmdline_main(config) -> None: ...
def configure_pytest_logging(config, plugin) -> None: ...
def pytest_configure(config) -> None: ...
def pytest_collection_modifyitems(config, items) -> None: ...
def pytest_runtest_setup(item) -> None: ...
