from _typeshed import Incomplete

class Relais8:
    def __init__(self, **args) -> None: ...
    def read(self, size): ...
    def write_config_request(self, address) -> None: ...
    def write(self, data) -> None: ...
    def set_all_outputs(self, status, reset: bool = False) -> None: ...
    def set_output(self, number, status) -> None: ...
    def get_output(self, number): ...
    def __del__(self) -> None: ...

def handle_set(busnum, devnum, number, status) -> None: ...
def handle_get(busnum, devnum, number): ...

methods: Incomplete
