from _typeshed import Incomplete

CLONE_NEWNS: int
CLONE_NEWUSER: int
CLONE_NEWNET: int
libc: Incomplete
socket_table: Incomplete

def b2s(b): ...
def s2b(s): ...
def py2s(o): ...
def s2py(s): ...
def unshare(flags): ...
def setns(fd, nstype: int = 0): ...

unshared: bool

def handle_unshare(): ...
def handle_create_tun(*, address=None): ...
def handle_socket(*args, **kwargs): ...
def handle_socket_close(sockid) -> None: ...
def handle_socket_dup(sockid): ...
def handle_socket_call(sockid, func, args, kwargs): ...
def handle_list_sockets(): ...
def handle_get_links(): ...
def handle_get_prefix(): ...
def handle_get_pid(): ...
def handle_get_intf(): ...
def handle_getaddrinfo(*args, **kwargs): ...

methods: Incomplete
