import threading

from _typeshed import Incomplete

class Future:
    def __init__(self) -> None: ...
    def set(self, result) -> None: ...
    def wait(self): ...

class BackgroundLoop(threading.Thread):
    def __init__(self) -> None: ...
    def run(self) -> None: ...
    def block_on(self, func, *args, **kwargs): ...

def address_from_str(s): ...
def connection_from_dict(data): ...

class NMDev:
    def __init__(self, interface) -> None: ...
    def get_settings(self): ...
    def get_active_settings(self): ...
    def configure(self, data) -> None: ...
    def wait_state(self, expected, timeout) -> None: ...
    def disable(self) -> None: ...
    def get_state(self): ...
    def request_scan(self) -> None: ...
    def get_access_points(self, scan): ...
    def get_dhcpd_leases(self): ...

bl: Incomplete
nm: Incomplete

def handle_configure(interface, settings): ...
def handle_wait_state(interface, expected, timeout: int = 60): ...
def handle_disable(interface): ...
def handle_get_active_settings(interface): ...
def handle_get_settings(interface): ...
def handle_get_state(interface): ...
def handle_get_dhcpd_leases(interface): ...
def handle_request_scan(interface): ...
def handle_get_access_points(interface, scan=None): ...

methods: Incomplete
