from _typeshed import Incomplete

class GpioDigitalOutput:
    gpio_sysfs_value_fd: Incomplete
    def __init__(self, index) -> None: ...
    def __del__(self) -> None: ...
    def get(self): ...
    def set(self, status) -> None: ...

def handle_set(index, status) -> None: ...
def handle_get(index): ...

methods: Incomplete
