from _typeshed import Incomplete

class UDisks2Device:
    UNMOUNT_MAX_RETRIES: int
    UNMOUNT_BUSY_WAIT: int
    devpath: Incomplete
    fs: Incomplete
    def __init__(self, devpath) -> None: ...
    def mount(self, readonly: bool = False, retries: int = 0): ...
    def unmount(self, lazy: bool = False) -> None: ...

def handle_mount(devpath, retries: int = 0): ...
def handle_unmount(devpath, lazy: bool = False): ...

methods: Incomplete
