from _typeshed import Incomplete

GET_REPORT: int
SET_REPORT: int
REPORT_TYPE_FEATURE: int

class USBHIDRelay:
    def __init__(self, **args) -> None: ...
    def set_output(self, number, status) -> None: ...
    def get_output(self, number): ...

def handle_set(busnum, devnum, number, status) -> None: ...
def handle_get(busnum, devnum, number): ...

methods: Incomplete
