from _typeshed import Incomplete

from ..binding import BindingError as BindingError
from ..driver import Driver as Driver

def never_retry(func): ...

class StrategyError(Exception):
    msg: Incomplete

class Strategy(Driver):
    broken: Incomplete
    def __attrs_post_init__(self) -> None: ...
    def on_client_bound(self, client) -> None: ...
    def on_activate(self) -> None: ...
    def on_deactivate(self) -> None: ...
    def resolve_conflicts(self, client) -> None: ...
    def transition(self, status) -> None: ...
    def force(self, status) -> None: ...
    def prepare_export(self): ...
