from _typeshed import Incomplete

from ..step import step as step
from .common import Strategy as Strategy
from .common import StrategyError as StrategyError

class GraphStrategyError(StrategyError): ...
class InvalidGraphStrategyError(GraphStrategyError): ...
class GraphStrategyRuntimeError(GraphStrategyError): ...

class GraphStrategy(Strategy):
    states: Incomplete
    root_state: Incomplete
    def __attrs_post_init__(self) -> None: ...
    path: Incomplete
    def invalidate(self) -> None: ...
    def transition(self, state, via=None): ...
    def find_abs_path(self, state, via=None): ...
    def find_rel_path(self, path): ...
    @property
    def graph(self): ...
    @classmethod
    def depends(cls, *dependencies): ...
