import argparse
import asyncio
import enum
from collections.abc import Sequence
from typing import Any

from _typeshed import Incomplete
from exceptiongroup import ExceptionGroup

from .. import Environment as Environment
from .. import Target as Target
from .. import target_factory as target_factory
from ..driver import ExecutionError as ExecutionError
from ..driver import Mode as Mode
from ..exceptions import InvalidConfigError as InvalidConfigError
from ..exceptions import NoDriverFoundError as NoDriverFoundError
from ..exceptions import NoResourceFoundError as NoResourceFoundError
from ..logging import StepLogger as StepLogger
from ..logging import basicConfig as basicConfig
from ..resource.remote import RemotePlace as RemotePlace
from ..resource.remote import RemotePlaceManager as RemotePlaceManager
from ..util import Timeout as Timeout
from ..util import atomic_replace as atomic_replace
from ..util import diff_dict as diff_dict
from ..util import dump as dump
from ..util import flat_dict as flat_dict
from ..util import labgrid_version as labgrid_version
from ..util.helper import processwrapper as processwrapper
from ..util.proxy import proxymanager as proxymanager
from .common import TAG_KEY as TAG_KEY
from .common import TAG_VAL as TAG_VAL
from .common import Place as Place
from .common import Reservation as Reservation
from .common import ReservationState as ReservationState
from .common import ResourceEntry as ResourceEntry
from .common import ResourceMatch as ResourceMatch
from .common import queue_as_aiter as queue_as_aiter
from .generated import labgrid_coordinator_pb2 as labgrid_coordinator_pb2
from .generated import labgrid_coordinator_pb2_grpc as labgrid_coordinator_pb2_grpc

class Error(Exception): ...
class UserError(Error): ...
class ServerError(Error): ...

class InteractiveCommandError(Error):
    exitcode: Incomplete
    def __init__(self, msg: str, exitcode: int) -> None: ...

class ErrorGroup(ExceptionGroup): ...

class ClientSession:
    address: Incomplete
    loop: Incomplete
    env: Incomplete
    role: Incomplete
    prog: Incomplete
    args: Incomplete
    monitor: Incomplete
    def gethostname(self): ...
    def getuser(self): ...
    stopping: Incomplete
    channel: Incomplete
    stub: Incomplete
    out_queue: Incomplete
    stream_call: Incomplete
    pump_task: Incomplete
    sync_id: Incomplete
    sync_events: Incomplete
    def __attrs_post_init__(self) -> None: ...
    resources: Incomplete
    places: Incomplete
    async def start(self) -> None: ...
    async def stop(self) -> None: ...
    async def close(self) -> None: ...
    async def sync_with_coordinator(self): ...
    def cancel_pending_syncs(self) -> None: ...
    async def message_pump(self) -> None: ...
    async def on_resource_changed(self, exporter, group_name, resource_name, resource) -> None: ...
    async def on_place_changed(self, place_pb2: labgrid_coordinator_pb2.Place): ...
    async def on_place_deleted(self, name: str): ...
    async def do_monitor(self) -> None: ...
    async def complete(self) -> None: ...
    async def print_resources(self): ...
    async def print_places(self): ...
    def print_who(self) -> None: ...
    def get_place(self, place=None): ...
    def get_place_names_from_env(self): ...
    def get_idle_place(self, place=None): ...
    def get_acquired_place(self, place=None): ...
    async def print_place(self) -> None: ...
    async def add_place(self) -> None: ...
    async def del_place(self) -> None: ...
    async def add_alias(self) -> None: ...
    async def del_alias(self) -> None: ...
    async def set_comment(self) -> None: ...
    async def set_tags(self) -> None: ...
    async def add_match(self) -> None: ...
    async def del_match(self) -> None: ...
    async def add_named_match(self) -> None: ...
    def check_matches(self, place) -> None: ...
    async def acquire(self) -> None: ...
    async def release(self) -> None: ...
    async def release_from(self) -> None: ...
    async def allow(self) -> None: ...
    def get_target_resources(self, place): ...
    def get_target_config(self, place): ...
    def print_env(self) -> None: ...
    def power(self) -> None: ...
    def digital_io(self) -> None: ...
    async def console(self, place, target) -> None: ...
    def dfu(self) -> None: ...
    def fastboot(self) -> None: ...
    def flashscript(self) -> None: ...
    def bootstrap(self) -> None: ...
    def sd_mux(self) -> None: ...
    def usb_mux(self) -> None: ...
    def ssh(self) -> None: ...
    def scp(self) -> None: ...
    def rsync(self) -> None: ...
    def sshfs(self) -> None: ...
    def forward(self) -> None: ...
    def telnet(self) -> None: ...
    def video(self) -> None: ...
    def audio(self) -> None: ...
    def netns(self) -> None: ...
    def tmc_command(self) -> None: ...
    def tmc_query(self) -> None: ...
    def tmc_screen(self) -> None: ...
    def tmc_channel(self) -> None: ...
    def write_files(self) -> None: ...
    def write_image(self) -> None: ...
    async def create_reservation(self) -> None: ...
    async def cancel_reservation(self) -> None: ...
    async def wait_reservation(self) -> None: ...
    async def print_reservations(self): ...
    async def export(self, place, target) -> None: ...
    def print_version(self) -> None: ...

def ensure_event_loop(external_loop=None): ...
def start_session(
    address: str,
    *,
    extra: dict[str, Any] | None = None,
    debug: bool = False,
    loop: asyncio.AbstractEventLoop | None = None,
): ...
def find_role_by_place(config, place): ...
def find_any_role_with_place(config): ...

class LocalPort(argparse.Action):
    def __init__(self, option_strings, dest, nargs=None, **kwargs) -> None: ...
    def __call__(
        self,
        parser: argparse.ArgumentParser,
        namespace: argparse.Namespace,
        values: str | Sequence[Any] | None,
        option_string: str | None = None,
    ) -> None: ...

class RemotePort(argparse.Action):
    def __init__(self, option_strings, dest, nargs=None, **kwargs) -> None: ...
    def __call__(
        self,
        parser: argparse.ArgumentParser,
        namespace: argparse.Namespace,
        values: str | Sequence[Any] | None,
        option_string: str | None = None,
    ) -> None: ...

class ExportFormat(enum.Enum):
    SHELL = "shell"
    SHELL_EXPORT = "shell-export"
    JSON = "json"

class AutoProgramArgumentParser(argparse.ArgumentParser):
    class _ActionWrapper:
        action: Incomplete
        def __init__(self, action) -> None: ...
        def add_parser(self, name, **kwargs): ...

    def __init__(self, *args, **kwargs) -> None: ...
    def add_subparsers(self, **kwargs): ...
    def add_argument(self, *args, **kwargs): ...

def get_parser(auto_doc_mode: bool = False) -> argparse.ArgumentParser | AutoProgramArgumentParser: ...
def main(): ...
