import enum
from collections.abc import Generator

from _typeshed import Incomplete

from .generated import labgrid_coordinator_pb2 as labgrid_coordinator_pb2

TAG_KEY: Incomplete
TAG_VAL: Incomplete

def set_map_from_dict(m, d) -> None: ...
def build_dict_from_map(m): ...

class ResourceEntry:
    data: Incomplete
    def __attrs_post_init__(self) -> None: ...
    @property
    def acquired(self): ...
    @property
    def avail(self): ...
    @property
    def cls(self): ...
    @property
    def params(self): ...
    @property
    def args(self): ...
    @property
    def extra(self): ...
    def asdict(self): ...
    def update(self, data) -> None: ...
    def acquire(self, place_name) -> None: ...
    def release(self) -> None: ...
    def as_pb2(self): ...
    @staticmethod
    def data_from_pb2(pb2): ...
    @classmethod
    def from_pb2(cls, pb2): ...

class ResourceMatch:
    exporter: Incomplete
    group: Incomplete
    cls: Incomplete
    name: Incomplete
    rename: Incomplete
    @classmethod
    def fromstr(cls, pattern): ...
    def ismatch(self, resource_path): ...
    def as_pb2(self): ...
    @classmethod
    def from_pb2(cls, pb2): ...

class Place:
    name: Incomplete
    aliases: Incomplete
    comment: Incomplete
    tags: Incomplete
    matches: Incomplete
    acquired: Incomplete
    acquired_resources: Incomplete
    allowed: Incomplete
    created: Incomplete
    changed: Incomplete
    reservation: Incomplete
    def asdict(self): ...
    def update_from_pb2(self, place_pb2) -> None: ...
    def show(self, level: int = 0) -> None: ...
    def getmatch(self, resource_path): ...
    def hasmatch(self, resource_path): ...
    def unmatched(self, resource_paths): ...
    def touch(self) -> None: ...
    def as_pb2(self): ...
    @classmethod
    def from_pb2(cls, pb2): ...

class ReservationState(enum.Enum):
    waiting = 0
    allocated = 1
    acquired = 2
    expired = 3
    invalid = 4

class Reservation:
    owner: Incomplete
    token: Incomplete
    state: Incomplete
    prio: Incomplete
    filters: Incomplete
    allocations: Incomplete
    created: Incomplete
    timeout: Incomplete
    def asdict(self): ...
    def refresh(self, delta: int = 60) -> None: ...
    @property
    def expired(self): ...
    def show(self, level: int = 0) -> None: ...
    def as_pb2(self): ...
    @classmethod
    def from_pb2(cls, pb2: labgrid_coordinator_pb2.Reservation): ...

async def queue_as_aiter(q) -> Generator[Incomplete]: ...
