from collections.abc import Generator
from contextlib import contextmanager
from enum import Enum

from _typeshed import Incomplete

from ..util import Timeout as Timeout
from ..util import atomic_replace as atomic_replace
from ..util import labgrid_version as labgrid_version
from ..util import yaml as yaml
from .common import TAG_KEY as TAG_KEY
from .common import TAG_VAL as TAG_VAL
from .common import Place as Place
from .common import Reservation as Reservation
from .common import ReservationState as ReservationState
from .common import ResourceEntry as ResourceEntry
from .common import ResourceMatch as ResourceMatch
from .common import queue_as_aiter as queue_as_aiter
from .generated import labgrid_coordinator_pb2 as labgrid_coordinator_pb2
from .generated import labgrid_coordinator_pb2_grpc as labgrid_coordinator_pb2_grpc
from .scheduler import TagSet as TagSet
from .scheduler import schedule as schedule

@contextmanager
def warn_if_slow(prefix, *, level=..., limit: float = 0.1) -> Generator[None]: ...

class Action(Enum):
    ADD = 0
    DEL = 1
    UPD = 2

class RemoteSession:
    coordinator: Incomplete
    peer: Incomplete
    name: Incomplete
    queue: Incomplete
    version: Incomplete

class ExporterSession(RemoteSession):
    groups: Incomplete
    def set_resource(self, groupname, resourcename, resource): ...
    def get_resources(self): ...

class ClientSession(RemoteSession):
    def subscribe_places(self) -> None: ...
    def subscribe_resources(self) -> None: ...

class ResourceImport(ResourceEntry):
    path: Incomplete
    orphaned: Incomplete

def locked(func): ...

class ExporterCommand:
    request: Incomplete
    response: Incomplete
    completed: Incomplete
    expired: bool
    def __init__(self, request) -> None: ...
    def complete(self, response) -> None: ...
    async def wait(self) -> None: ...

class ExporterError(Exception): ...

class Coordinator(labgrid_coordinator_pb2_grpc.CoordinatorServicer):
    places: dict[str, Place]
    reservations: Incomplete
    poll_tasks: Incomplete
    save_scheduled: bool
    lock: Incomplete
    exporters: dict[str, ExporterSession]
    clients: dict[str, ClientSession]
    loop: Incomplete
    def __init__(self) -> None: ...
    async def poll(self, step_func) -> None: ...
    def save_later(self) -> None: ...
    async def save(self) -> None: ...
    def load(self) -> None: ...
    async def ClientStream(self, request_iterator, context) -> Generator[Incomplete]: ...
    def get_exporter_by_name(self, name): ...
    async def ExporterStream(self, request_iterator, context) -> Generator[Incomplete]: ...
    @locked
    async def AddPlace(self, request, context): ...
    @locked
    async def DeletePlace(self, request, context): ...
    @locked
    async def AddPlaceAlias(self, request, context): ...
    @locked
    async def DeletePlaceAlias(self, request, context): ...
    @locked
    async def SetPlaceTags(self, request, context): ...
    @locked
    async def SetPlaceComment(self, request, context): ...
    @locked
    async def AddPlaceMatch(self, request, context): ...
    @locked
    async def DeletePlaceMatch(self, request, context): ...
    @locked
    async def AcquirePlace(self, request, context): ...
    @locked
    async def ReleasePlace(self, request, context): ...
    @locked
    async def AllowPlace(self, request, context): ...
    @locked
    async def GetPlaces(self, unused_request, unused_context): ...
    def schedule_reservations(self): ...
    @locked
    async def CreateReservation(self, request: labgrid_coordinator_pb2.CreateReservationRequest, context): ...
    @locked
    async def CancelReservation(self, request: labgrid_coordinator_pb2.CancelReservationRequest, context): ...
    @locked
    async def PollReservation(self, request: labgrid_coordinator_pb2.PollReservationRequest, context): ...
    @locked
    async def GetReservations(self, request: labgrid_coordinator_pb2.GetReservationsRequest, context): ...

async def serve(listen, cleanup) -> None: ...
def main() -> None: ...
