from _typeshed import Incomplete

from ..util import get_free_port as get_free_port
from ..util import labgrid_version as labgrid_version
from .common import ResourceEntry as ResourceEntry
from .common import queue_as_aiter as queue_as_aiter
from .config import ResourceConfig as ResourceConfig
from .generated import labgrid_coordinator_pb2 as labgrid_coordinator_pb2
from .generated import labgrid_coordinator_pb2_grpc as labgrid_coordinator_pb2_grpc

exports: dict[str, type[ResourceEntry]]
reexec: bool

class ExporterError(Exception): ...
class BrokenResourceError(ExporterError): ...
class UnknownResourceError(ExporterError): ...
class InvalidResourceRequestError(ExporterError): ...

def log_subprocess_kernel_stack(logger, child) -> None: ...

class ResourceExport(ResourceEntry):
    host: Incomplete
    proxy: Incomplete
    proxy_required: Incomplete
    local: Incomplete
    local_params: Incomplete
    start_params: Incomplete
    logger: Incomplete
    def __attrs_post_init__(self) -> None: ...
    @property
    def broken(self): ...
    @broken.setter
    def broken(self, reason) -> None: ...
    def start(self) -> None: ...
    def stop(self) -> None: ...
    def poll(self): ...
    def acquire(self, *args, **kwargs) -> None: ...
    def release(self, *args, **kwargs) -> None: ...

class SerialPortExport(ResourceExport):
    local: Incomplete
    child: Incomplete
    port: Incomplete
    ser2net_bin: Incomplete
    def __attrs_post_init__(self) -> None: ...
    def __del__(self) -> None: ...

class NetworkInterfaceExport(ResourceExport):
    local: Incomplete
    def __attrs_post_init__(self) -> None: ...

class USBGenericExport(ResourceExport):
    local: Incomplete
    def __attrs_post_init__(self) -> None: ...

class USBSigrokExport(USBGenericExport):
    def __attrs_post_init__(self) -> None: ...

class USBSDMuxExport(USBGenericExport):
    def __attrs_post_init__(self) -> None: ...

class USBSDWireExport(USBGenericExport):
    def __attrs_post_init__(self) -> None: ...

class USBSDWire3Export(USBGenericExport):
    def __attrs_post_init__(self) -> None: ...

class USBAudioInputExport(USBGenericExport):
    def __attrs_post_init__(self) -> None: ...

class SiSPMPowerPortExport(USBGenericExport):
    def __attrs_post_init__(self) -> None: ...

class USBPowerPortExport(USBGenericExport):
    def __attrs_post_init__(self) -> None: ...

class USBDeditecRelaisExport(USBGenericExport):
    def __attrs_post_init__(self) -> None: ...

class USBHIDRelayExport(USBGenericExport):
    def __attrs_post_init__(self) -> None: ...

class USBFlashableExport(USBGenericExport):
    def __attrs_post_init__(self) -> None: ...

class USBGenericRemoteExport(USBGenericExport):
    def __attrs_post_init__(self) -> None: ...

class ProviderGenericExport(ResourceExport):
    local: Incomplete
    def __attrs_post_init__(self) -> None: ...

class EthernetPortExport(ResourceExport):
    local: Incomplete
    def __attrs_post_init__(self) -> None: ...

class GPIOSysFSExport(ResourceExport):
    local: Incomplete
    export_path: Incomplete
    system_exported: bool
    def __attrs_post_init__(self) -> None: ...

class NetworkServiceExport(ResourceExport):
    local: Incomplete
    proxy_required: bool
    def __attrs_post_init__(self) -> None: ...

class HTTPVideoStreamExport(ResourceExport):
    local: Incomplete
    def __attrs_post_init__(self) -> None: ...

class LXAIOBusNodeExport(ResourceExport):
    local: Incomplete
    def __attrs_post_init__(self) -> None: ...

class AndroidNetFastbootExport(ResourceExport):
    local: Incomplete
    def __attrs_post_init__(self) -> None: ...

class YKUSHPowerPortExport(ResourceExport):
    local: Incomplete
    def __attrs_post_init__(self) -> None: ...

class Exporter:
    config: Incomplete
    loop: Incomplete
    name: Incomplete
    hostname: Incomplete
    isolated: Incomplete
    channel: Incomplete
    stub: Incomplete
    out_queue: Incomplete
    pump_task: Incomplete
    poll_task: Incomplete
    groups: Incomplete
    def __init__(self, config) -> None: ...
    async def run(self) -> None: ...
    def send_started(self) -> None: ...
    async def message_pump(self) -> None: ...
    async def acquire(self, group_name, resource_name, place_name) -> None: ...
    async def release(self, group_name, resource_name) -> None: ...
    async def poll(self) -> None: ...
    async def add_resource(self, group_name, resource_name, cls, params) -> None: ...
    async def update_resource(self, group_name, resource_name) -> None: ...

async def amain(config) -> bool: ...
def main() -> None: ...
