from _typeshed import Incomplete

from .exceptions import InvalidConfigError as InvalidConfigError
from .exceptions import NoConfigFoundError as NoConfigFoundError
from .util.yaml import load as load
from .util.yaml import resolve_templates as resolve_templates

class Config:
    filename: Incomplete
    base: Incomplete
    data: Incomplete
    def __attrs_post_init__(self) -> None: ...
    def resolve_path(self, path): ...
    def resolve_path_str_or_list(self, path): ...
    def get_tool(self, tool): ...
    def get_image_path(self, kind): ...
    def get_path(self, kind): ...
    def get_option(self, name, default=None): ...
    def set_option(self, name, value) -> None: ...
    def get_target_option(self, target, name, default=None): ...
    def set_target_option(self, target, name, value) -> None: ...
    def get_targets(self): ...
    def get_imports(self): ...
    def get_paths(self): ...
    def get_images(self): ...
    def get_features(self): ...
