from _typeshed import Incomplete

from .step import steps as steps

class ConsoleLoggingReporter:
    instance: Incomplete
    @classmethod
    def start(cls, path) -> None: ...
    @classmethod
    def stop(cls) -> None: ...
    logpath: Incomplete
    def __init__(self, logpath) -> None: ...
    def get_logfile(self, event): ...
    def notify(self, event) -> None: ...
