from _typeshed import Incomplete

from .config import Config as Config
from .target import Target as Target

class Environment:
    config_file: Incomplete
    interact: Incomplete
    targets: Incomplete
    config: Incomplete
    def __attrs_post_init__(self) -> None: ...
    def get_target(self, role: str = "main") -> Target | None: ...
    def get_features(self): ...
    def get_target_features(self): ...
    def cleanup(self) -> None: ...
