from _typeshed import Incomplete

from .exceptions import InvalidConfigError as InvalidConfigError
from .exceptions import RegistrationError as RegistrationError
from .util.dict import filter_dict as filter_dict

class TargetFactory:
    resources: Incomplete
    drivers: Incomplete
    all_classes: Incomplete
    def __init__(self) -> None: ...
    def reg_resource(self, cls): ...
    def reg_driver(self, cls): ...
    @staticmethod
    def normalize_config(config): ...
    def make_resource(self, target, resource, name, args): ...
    def make_driver(self, target, driver, name, args): ...
    def make_target(self, name, config, *, env=None): ...
    def class_from_string(self, string: str): ...

target_factory: Incomplete
