from _typeshed import Incomplete

from .step import StepEvent as StepEvent
from .step import steps as steps
from .util import re_vt100 as re_vt100

DEFAULT_FORMAT: str

def basicConfig(**kwargs) -> None: ...

class StepFormatter:
    formatter: Incomplete
    indent: Incomplete
    indent_level: int
    bufs: Incomplete
    color: Incomplete
    def __init__(self, *args, indent: bool = True, color=None, parent=None, **kwargs) -> None: ...
    def format(self, record): ...

class SerialLoggingReporter:
    bufs: Incomplete
    loggers: Incomplete
    lastevent: Incomplete
    def __attrs_post_init__(self) -> None: ...
    def vt100_replace_cr_nl(self, buf): ...
    def notify(self, event) -> None: ...
    def flush(self) -> None: ...

class StepLogger:
    def __attrs_post_init__(self) -> None: ...
    @classmethod
    def start(cls, length_limit=None) -> None: ...
    @classmethod
    def stop(cls) -> None: ...
    @classmethod
    def get_prefix(cls, event): ...
    @staticmethod
    def format_arguments(args): ...
    @staticmethod
    def format_duration(duration): ...
    @classmethod
    def format_result(cls, result): ...
    @classmethod
    def get_next_indent(cls, event): ...
    @classmethod
    def notify(cls, event) -> None: ...
