from .step import steps as steps

class StepReporter:
    def __init__(self) -> None: ...
    @classmethod
    def start(cls) -> None: ...
    @classmethod
    def stop(cls) -> None: ...
    @staticmethod
    def notify(event) -> None: ...
