from _typeshed import Incomplete

class Steps:
    def __init__(self) -> None: ...
    def get_current(self): ...
    def get_new(self, title, tag, source, sourceinfo): ...
    def push(self, step) -> None: ...
    def pop(self, step) -> None: ...
    def subscribe(self, callback) -> None: ...
    def unsubscribe(self, callback) -> None: ...
    def notify(self, event) -> None: ...

steps: Incomplete

class StepEvent:
    ts: Incomplete
    step: Incomplete
    data: Incomplete
    resource: Incomplete
    stream: Incomplete
    def __init__(self, current_step: Step, data, *, resource=None, stream: bool = False) -> None: ...
    def __setitem__(self, k, v) -> None: ...
    def merge(self, other): ...
    @property
    def age(self): ...

class Step:
    title: Incomplete
    level: Incomplete
    tag: Incomplete
    source: Incomplete
    sourceinfo: Incomplete
    args: Incomplete
    result: Incomplete
    exception: Incomplete
    def __init__(self, title, level, tag, source, sourceinfo) -> None: ...
    @property
    def duration(self): ...
    @property
    def status(self): ...
    @property
    def is_active(self): ...
    @property
    def is_done(self): ...
    def start(self) -> None: ...
    def skip(self, reason) -> None: ...
    def stop(self) -> None: ...
    def __del__(self) -> None: ...

def step(*, title=None, args=[], result: bool = False, tag=None): ...
