from _typeshed import Incomplete

from .binding import BindingError as BindingError
from .binding import BindingState as BindingState
from .driver import Driver as Driver
from .exceptions import NoDriverFoundError as NoDriverFoundError
from .exceptions import NoResourceFoundError as NoResourceFoundError
from .exceptions import NoStrategyFoundError as NoStrategyFoundError
from .exceptions import NoSupplierFoundError as NoSupplierFoundError
from .factory import target_factory as target_factory
from .resource import Resource as Resource
from .strategy import Strategy as Strategy
from .util import Timeout as Timeout

class Target:
    name: Incomplete
    env: Incomplete
    log: Incomplete
    resources: Incomplete
    drivers: Incomplete
    last_update: float
    def __attrs_post_init__(self) -> None: ...
    def interact(self, msg) -> None: ...
    def update_resources(self) -> None: ...
    def await_resources(self, resources, timeout=None, avail: bool = True) -> None: ...
    def get_resource(self, cls, *, name=None, wait_avail: bool = True): ...
    def get_active_driver(self, cls, *, name=None, resource=None): ...
    def get_driver(self, cls, *, name=None, resource=None, activate: bool = True): ...
    def get_strategy(self): ...
    def __getitem__(self, key): ...
    def set_binding_map(self, mapping) -> None: ...
    def bind_resource(self, resource) -> None: ...
    def bind_driver(self, client) -> None: ...
    def bind(self, bindable): ...
    def activate(self, client, name=None) -> None: ...
    def deactivate(self, client, name=None): ...
    def deactivate_all_drivers(self) -> None: ...
    def export(self): ...
    def cleanup(self) -> None: ...
    def __enter__(self): ...
    def __exit__(self, *exc) -> None: ...
