from _typeshed import Incomplete

from ..binding import BindingMixin as BindingMixin
from ..util.ssh import sshmanager as sshmanager

class Resource(BindingMixin):
    avail: Incomplete
    logger: Incomplete
    def __attrs_post_init__(self) -> None: ...
    @property
    def command_prefix(self): ...
    def wrap_command(self, command): ...
    @property
    def parent(self): ...
    @parent.setter
    def parent(self, value) -> None: ...
    def get_managed_parent(self): ...
    def poll(self) -> None: ...
    def get_bound_resources(self): ...

class NetworkResource(Resource):
    host: Incomplete
    @property
    def command_prefix(self): ...
    def wrap_command(self, command): ...

class ResourceManager:
    instances: dict[type[ResourceManager], ResourceManager]
    @classmethod
    def get(cls) -> ResourceManager: ...
    resources: list[ManagedResource]
    logger: Incomplete
    def __attrs_post_init__(self) -> None: ...
    def on_resource_added(self, resource: ManagedResource): ...
    def poll(self) -> None: ...

class ManagedResource(Resource):
    manager_cls = ResourceManager
    timeout: Incomplete
    avail: bool
    manager: Incomplete
    def __attrs_post_init__(self) -> None: ...
    def poll(self) -> None: ...
    def get_managed_parent(self): ...
