from _typeshed import Incomplete

from ..factory import target_factory as target_factory
from ..util import Timeout as Timeout
from .base import NetworkInterface as NetworkInterface
from .base import SerialPort as SerialPort
from .common import ManagedResource as ManagedResource
from .common import ResourceManager as ResourceManager

class UdevManager(ResourceManager):
    queue: Incomplete
    def __attrs_post_init__(self) -> None: ...
    def on_resource_added(self, resource) -> None: ...
    def poll(self) -> None: ...

class USBResource(ManagedResource):
    manager_cls = UdevManager
    match: Incomplete
    device: Incomplete
    suggest: Incomplete
    timeout: float
    def __attrs_post_init__(self) -> None: ...
    def filter_match(self, device): ...
    def suggest_match(self, device): ...
    avail: Incomplete
    def try_match(self, device): ...
    def update(self) -> None: ...
    @property
    def busnum(self): ...
    @property
    def devnum(self): ...
    @property
    def path(self): ...
    @property
    def vendor_id(self): ...
    @property
    def model_id(self): ...
    def read_attr(self, attribute): ...

class USBSerialPort(USBResource, SerialPort):
    def __attrs_post_init__(self) -> None: ...
    port: Incomplete
    def update(self) -> None: ...

class USBMassStorage(USBResource):
    def __attrs_post_init__(self) -> None: ...
    @property
    def avail(self): ...
    @avail.setter
    def avail(self, prop) -> None: ...
    @property
    def path(self): ...

class IMXUSBLoader(USBResource):
    def filter_match(self, device): ...

class RKUSBLoader(USBResource):
    def filter_match(self, device): ...

class MXSUSBLoader(USBResource):
    def filter_match(self, device): ...

class AndroidUSBFastboot(USBResource):
    usb_vendor_id: Incomplete
    usb_product_id: Incomplete
    def filter_match(self, device): ...

class AndroidFastboot(AndroidUSBFastboot):
    def __attrs_post_init__(self) -> None: ...

class DFUDevice(USBResource):
    def filter_match(self, device): ...

class USBNetworkInterface(USBResource, NetworkInterface):
    def __attrs_post_init__(self) -> None: ...
    ifname: Incomplete
    def update(self) -> None: ...
    @property
    def if_state(self): ...

class AlteraUSBBlaster(USBResource):
    def filter_match(self, device): ...

class SigrokUSBDevice(USBResource):
    driver: Incomplete
    channels: Incomplete
    channel_group: Incomplete
    def __attrs_post_init__(self) -> None: ...

class SigrokUSBSerialDevice(USBResource):
    driver: Incomplete
    channels: Incomplete
    channel_group: Incomplete
    def __attrs_post_init__(self) -> None: ...
    @property
    def path(self): ...

class USBSDWireDevice(USBResource):
    disk_path: Incomplete
    control_serial: Incomplete
    def __attrs_post_init__(self) -> None: ...
    @property
    def avail(self): ...
    @avail.setter
    def avail(self, prop) -> None: ...
    def poll(self) -> None: ...
    def update(self) -> None: ...
    @property
    def path(self): ...

class USBSDWire3Device(USBResource):
    control_serial: Incomplete
    disk_path: Incomplete
    def __attrs_post_init__(self) -> None: ...
    @property
    def avail(self): ...
    @avail.setter
    def avail(self, prop) -> None: ...
    def poll(self) -> None: ...
    def update(self) -> None: ...
    @property
    def path(self): ...

class USBSDMuxDevice(USBResource):
    control_path: Incomplete
    disk_path: Incomplete
    def __attrs_post_init__(self) -> None: ...
    @property
    def avail(self): ...
    @avail.setter
    def avail(self, prop) -> None: ...
    def poll(self) -> None: ...
    def update(self) -> None: ...
    @property
    def path(self): ...

class USBHub(USBResource):
    def __attrs_post_init__(self) -> None: ...

class USBPowerPort(USBResource):
    index: Incomplete
    def __attrs_post_init__(self) -> None: ...

class SiSPMPowerPort(USBResource):
    index: Incomplete
    def filter_match(self, device): ...

class USBVideo(USBResource):
    def filter_match(self, device): ...
    def __attrs_post_init__(self) -> None: ...
    @property
    def path(self): ...

class USBAudioInput(USBResource):
    index: Incomplete
    def filter_match(self, device): ...
    def __attrs_post_init__(self) -> None: ...
    @property
    def path(self): ...
    @property
    def alsa_name(self): ...

class USBTMC(USBResource):
    def __attrs_post_init__(self) -> None: ...
    @property
    def path(self): ...

class DeditecRelais8(USBResource):
    index: Incomplete
    invert: Incomplete
    def __attrs_post_init__(self) -> None: ...

class HIDRelay(USBResource):
    index: Incomplete
    invert: Incomplete
    def filter_match(self, device): ...

class USBFlashableDevice(USBResource):
    @property
    def devnode(self): ...

class LXAUSBMux(USBResource):
    def __attrs_post_init__(self) -> None: ...

class USBDebugger(USBResource):
    def filter_match(self, device): ...

class MatchedSysfsGPIO(USBResource):
    pin: Incomplete
    index: Incomplete
    def __attrs_post_init__(self) -> None: ...
    def filter_match(self, device): ...
    def update(self) -> None: ...
