from ..exception import ExecutionError as ExecutionError

PORT: int
LOGIN_SUCCESS_REGEX: str
SOCKSTATES_REGEX: str

def login(base_url: str) -> None: ...
def logout(base_url: str) -> None: ...
def power_set(host, port, index, value) -> None: ...
def power_get(host, port, index): ...
