import requests

from ..exception import ExecutionError as ExecutionError

def login(s: requests.Session, base_url: str, credentials: dict) -> None: ...
def get_credentials(base_url: str) -> tuple[str, dict]: ...
def power_set(host, port, index, value) -> None: ...
def power_get(host, port, index): ...
