import abc

class CommandProtocol(abc.ABC):
    @abc.abstractmethod
    def run(self, command: str): ...
    @abc.abstractmethod
    def run_check(self, command: str): ...
    @abc.abstractmethod
    def get_status(self): ...
    @abc.abstractmethod
    def wait_for(self): ...
    @abc.abstractmethod
    def poll_until_success(self): ...
