import abc

class ConsoleProtocol(abc.ABC):
    @abc.abstractmethod
    def read(self): ...
    @abc.abstractmethod
    def write(self, data: bytes): ...
    def sendline(self, line: str): ...
    def sendcontrol(self, char: str): ...
    def expect(self, pattern: str): ...
    class Client(abc.ABC):
        @abc.abstractmethod
        def get_console_matches(self): ...
        @abc.abstractmethod
        def notify_console_match(self, pattern, match): ...
