from _typeshed import Incomplete

def b2s(b): ...
def s2b(s): ...
def py2s(o): ...
def s2py(s): ...

class Agent:
    methods: Incomplete
    stdin: Incomplete
    stdout: Incomplete
    fdpass: Incomplete
    def __init__(self) -> None: ...
    def send(self, data) -> None: ...
    def register(self, name, func) -> None: ...
    def load(self, name, source) -> None: ...
    def list(self): ...
    def run(self) -> None: ...

def handle_test(*args, **kwargs): ...
def handle_test_fd(): ...
def handle_error(message) -> None: ...
def handle_usbtmc(index, cmd, read: bool = False): ...
def main() -> None: ...
