from _typeshed import Incomplete

from .ssh import get_ssh_connect_timeout as get_ssh_connect_timeout

def b2s(b): ...
def s2b(s): ...

class AgentError(Exception): ...
class AgentException(Exception): ...

class MethodProxy:
    wrapper: Incomplete
    name: Incomplete
    def __init__(self, wrapper, name) -> None: ...
    def __call__(self, *args, **kwargs): ...

class ModuleProxy:
    wrapper: Incomplete
    name: Incomplete
    def __init__(self, wrapper, name) -> None: ...
    def __getattr__(self, name): ...

class AgentWrapper:
    agent: Incomplete
    loaded: Incomplete
    logger: Incomplete
    fdpass: Incomplete
    def __init__(self, host=None) -> None: ...
    def __del__(self) -> None: ...
    def __getattr__(self, name): ...
    def __enter__(self): ...
    def __exit__(self, *exc) -> None: ...
    def call(self, method, *args, **kwargs): ...
    def load(self, name, path=None): ...
    def close(self) -> None: ...
