from collections.abc import Generator

from _typeshed import Incomplete

def diff_dict(old, new) -> Generator[Incomplete]: ...
def flat_dict(d): ...
def filter_dict(d, cls, warn: bool = False): ...
def find_dict(d, key): ...
