import pexpect
from _typeshed import Incomplete

class PtxExpect(pexpect.spawn):
    driver: Incomplete
    linesep: bytes
    def __init__(self, driver) -> None: ...
    def send(self, s): ...
    def sendcontrol(self, char) -> None: ...
    def read_nonblocking(self, size: int = 1, timeout: int = -1): ...
