from _typeshed import Incomplete

from ..step import step as step

re_vt100: Incomplete

def get_free_port(): ...
def get_user(): ...
def set_nonblocking(fd) -> None: ...

class ProcessWrapper:
    callbacks: Incomplete
    loglevel: Incomplete
    def check_output(self, command, *, print_on_silent_log: bool = False, input=None, stdin=None): ...
    def register(self, callback) -> None: ...
    def unregister(self, callback) -> None: ...
    @staticmethod
    def log_callback(message, process) -> None: ...
    @staticmethod
    def print_callback(message, _) -> None: ...
    def enable_logging(self) -> None: ...
    def disable_logging(self) -> None: ...
    def enable_print(self) -> None: ...
    def disable_print(self) -> None: ...

processwrapper: Incomplete
