import contextlib
import functools
import socket
from collections.abc import Generator

from _typeshed import Incomplete

from . import get_free_port as get_free_port
from .agent import py2s as py2s
from .agent import s2py as s2py

class NSSocket(socket.socket):
    def __init__(self, *args, **kwargs) -> None: ...
    def close(self): ...
    def detach(self): ...
    def dup(self): ...

class NetNamespace:
    @classmethod
    def create(cls, agentwrapper, mac_address=None): ...
    logger: Incomplete
    def __init__(self, agent) -> None: ...
    @functools.cached_property
    def prefix(self): ...
    @functools.cached_property
    def intf(self): ...
    def ifindex(self): ...
    def get_links(self): ...
    def run(self, command, **kwargs): ...
    def Popen(self, command, **kwargs): ...
    def run_script(self, script, script_args=[], **kwargs): ...
    @contextlib.contextmanager
    def Popen_script(self, script, script_args=[], **kwargs) -> Generator[Incomplete]: ...
    def socket(self, *args, **kwargs): ...
    def getaddrinfo(self, *args, **kwargs): ...
    @contextlib.contextmanager
    def socks_proxy(self) -> Generator[Incomplete, None, Incomplete]: ...
