from collections.abc import Callable
from typing import Any, TypeVar

from _typeshed import Incomplete

from ..driver.exception import ExecutionError as ExecutionError
from .helper import get_free_port as get_free_port
from .helper import processwrapper as processwrapper

_F = TypeVar("_F", bound=Callable[..., Any])

def _check_connected(func: _F) -> _F: ...
def get_ssh_connect_timeout(): ...

class SSHConnectionManager:
    logger: Incomplete
    def __attrs_post_init__(self) -> None: ...
    def get(self, host: str): ...
    def add_connection(self, connection) -> None: ...
    def remove_connection(self, connection) -> None: ...
    def remove_by_name(self, name) -> None: ...
    def open(self, host): ...
    def close(self, host) -> None: ...
    def request_forward(self, host, dest, port): ...
    def remove_forward(self, host, dest, port) -> None: ...
    def put_file(self, host, local_file, remote_file) -> None: ...
    def get_file(self, host, remote_file, local_file) -> None: ...
    def close_all(self) -> None: ...

class SSHConnection:
    host: Incomplete
    def __attrs_post_init__(self) -> None: ...
    @_check_connected
    def get_prefix(self): ...
    @_check_connected
    def run(
        self,
        command,
        *,
        codec: str = "utf-8",
        decodeerrors: str = "strict",
        force_tty: bool = False,
        stderr_merge: bool = False,
        stderr_loglevel: Incomplete | None = None,
        stdout_loglevel: Incomplete | None = None,
    ): ...
    def run_check(
        self,
        command,
        *,
        codec: str = "utf-8",
        decodeerrors: str = "strict",
        force_tty: bool = False,
        stderr_merge: bool = False,
        stderr_loglevel: Incomplete | None = None,
        stdout_loglevel: Incomplete | None = None,
    ): ...
    @_check_connected
    def get_file(self, remote_file, local_file) -> None: ...
    @_check_connected
    def put_file(self, local_file, remote_path) -> None: ...
    @_check_connected
    def add_port_forward(self, remote_host, remote_port, local_port=None): ...
    @_check_connected
    def remove_port_forward(self, remote_host, remote_port) -> None: ...
    @_check_connected
    def add_remote_port_forward(self, remote_port, local_port, remote_bind=None) -> None: ...
    @_check_connected
    def remove_remote_port_forward(self, remote_port, local_port, remote_bind=None) -> None: ...
    def connect(self) -> None: ...
    def isconnected(self): ...
    @_check_connected
    def disconnect(self) -> None: ...
    def cleanup(self) -> None: ...

sshmanager: Incomplete

class ForwardError(Exception):
    msg: Incomplete
